name: mobile
description: "Application to Emulate a Parking Spot"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  flutter_dotenv: ^5.2.1
  jwt_decoder: ^2.0.1
  flutter_secure_storage: ^9.2.4

  grpc: ^4.0.4
  go_router: ^14.8.1
  get_it: ^8.0.3
  provider: ^6.1.4
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  protobuf: ^4.0.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Black.ttf
          weight: 900
        - asset: fonts/Lato-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: fonts/Lato-Bold.ttf
          weight: 700
        - asset: fonts/Lato-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Lato-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/Lato-Light.ttf
          weight: 300
        - asset: fonts/Lato-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Lato-Regular.ttf
          weight: 400
        - asset: fonts/Lato-Thin.ttf
          weight: 100
        - asset: fonts/Lato-ThinItalic.ttf
          weight: 100
          style: italic
    - family: Bowlby One
      fonts:
        - asset: fonts/BowlbyOne-Regular.ttf
          weight: 400
          style: normal

  assets:
    - .env
