name: mobile
description: "Application to Emulate a Parking Spot"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  flutter_dotenv: ^5.2.1
  jwt_decoder: ^2.0.1
  flutter_secure_storage: ^9.2.4

  grpc: ^4.0.4
  go_router: ^14.8.1
  get_it: ^8.0.3
  provider: ^6.1.4
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  protobuf: ^4.0.0
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - .env