services:
  server:
    container_name: raspberry_pi
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    ports:
      - ${GRPC_SERVER_PORT}:${GRPC_SERVER_PORT}
      - ${HTTP_SERVER_PORT}:${HTTP_SERVER_PORT}
    devices:
      - "/dev/rfcomm0:/dev/rfcomm0"
    group_add:
      - "dialout"
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_started

  redis:
    container_name: redis
    image: redis/redis-stack:latest
    ports:
      - "${REDIS_PORT}:6379"
      - "${REDIS_UI_PORT}:8001"
