// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: parksense.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LotState int32

const (
	LotState_UNKNOWN  LotState = 0
	LotState_FREE     LotState = 1
	LotState_OCCUPIED LotState = 2
	LotState_RESERVED LotState = 3
)

// Enum value maps for LotState.
var (
	LotState_name = map[int32]string{
		0: "UNKNOWN",
		1: "FREE",
		2: "OCCUPIED",
		3: "RESERVED",
	}
	LotState_value = map[string]int32{
		"UNKNOWN":  0,
		"FREE":     1,
		"OCCUPIED": 2,
		"RESERVED": 3,
	}
)

func (x LotState) Enum() *LotState {
	p := new(LotState)
	*p = x
	return p
}

func (x LotState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LotState) Descriptor() protoreflect.EnumDescriptor {
	return file_parksense_proto_enumTypes[0].Descriptor()
}

func (LotState) Type() protoreflect.EnumType {
	return &file_parksense_proto_enumTypes[0]
}

func (x LotState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LotState.Descriptor instead.
func (LotState) EnumDescriptor() ([]byte, []int) {
	return file_parksense_proto_rawDescGZIP(), []int{0}
}

type ParkState int32

const (
	ParkState_NORMAL ParkState = 0
	ParkState_FIRE   ParkState = 1
)

// Enum value maps for ParkState.
var (
	ParkState_name = map[int32]string{
		0: "NORMAL",
		1: "FIRE",
	}
	ParkState_value = map[string]int32{
		"NORMAL": 0,
		"FIRE":   1,
	}
)

func (x ParkState) Enum() *ParkState {
	p := new(ParkState)
	*p = x
	return p
}

func (x ParkState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ParkState) Descriptor() protoreflect.EnumDescriptor {
	return file_parksense_proto_enumTypes[1].Descriptor()
}

func (ParkState) Type() protoreflect.EnumType {
	return &file_parksense_proto_enumTypes[1]
}

func (x ParkState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ParkState.Descriptor instead.
func (ParkState) EnumDescriptor() ([]byte, []int) {
	return file_parksense_proto_rawDescGZIP(), []int{1}
}

type ParkLot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParkLotId     string                 `protobuf:"bytes,1,opt,name=park_lot_id,json=parkLotId,proto3" json:"park_lot_id,omitempty"`
	State         LotState               `protobuf:"varint,2,opt,name=state,proto3,enum=parksense.LotState" json:"state,omitempty"`
	Row           uint32                 `protobuf:"varint,3,opt,name=row,proto3" json:"row,omitempty"`
	Column        uint32                 `protobuf:"varint,4,opt,name=column,proto3" json:"column,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParkLot) Reset() {
	*x = ParkLot{}
	mi := &file_parksense_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParkLot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParkLot) ProtoMessage() {}

func (x *ParkLot) ProtoReflect() protoreflect.Message {
	mi := &file_parksense_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParkLot.ProtoReflect.Descriptor instead.
func (*ParkLot) Descriptor() ([]byte, []int) {
	return file_parksense_proto_rawDescGZIP(), []int{0}
}

func (x *ParkLot) GetParkLotId() string {
	if x != nil {
		return x.ParkLotId
	}
	return ""
}

func (x *ParkLot) GetState() LotState {
	if x != nil {
		return x.State
	}
	return LotState_UNKNOWN
}

func (x *ParkLot) GetRow() uint32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *ParkLot) GetColumn() uint32 {
	if x != nil {
		return x.Column
	}
	return 0
}

type ParkSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParkSetId     string                 `protobuf:"bytes,1,opt,name=park_set_id,json=parkSetId,proto3" json:"park_set_id,omitempty"`
	Lots          []*ParkLot             `protobuf:"bytes,2,rep,name=lots,proto3" json:"lots,omitempty"`
	State         ParkState              `protobuf:"varint,3,opt,name=state,proto3,enum=parksense.ParkState" json:"state,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParkSet) Reset() {
	*x = ParkSet{}
	mi := &file_parksense_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParkSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParkSet) ProtoMessage() {}

func (x *ParkSet) ProtoReflect() protoreflect.Message {
	mi := &file_parksense_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParkSet.ProtoReflect.Descriptor instead.
func (*ParkSet) Descriptor() ([]byte, []int) {
	return file_parksense_proto_rawDescGZIP(), []int{1}
}

func (x *ParkSet) GetParkSetId() string {
	if x != nil {
		return x.ParkSetId
	}
	return ""
}

func (x *ParkSet) GetLots() []*ParkLot {
	if x != nil {
		return x.Lots
	}
	return nil
}

func (x *ParkSet) GetState() ParkState {
	if x != nil {
		return x.State
	}
	return ParkState_NORMAL
}

func (x *ParkSet) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type Reserve struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReserveId     string                 `protobuf:"bytes,1,opt,name=reserve_id,json=reserveId,proto3" json:"reserve_id,omitempty"`
	SlotId        string                 `protobuf:"bytes,2,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	SlotLabel     string                 `protobuf:"bytes,3,opt,name=slot_label,json=slotLabel,proto3" json:"slot_label,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reserve) Reset() {
	*x = Reserve{}
	mi := &file_parksense_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reserve) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reserve) ProtoMessage() {}

func (x *Reserve) ProtoReflect() protoreflect.Message {
	mi := &file_parksense_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reserve.ProtoReflect.Descriptor instead.
func (*Reserve) Descriptor() ([]byte, []int) {
	return file_parksense_proto_rawDescGZIP(), []int{2}
}

func (x *Reserve) GetReserveId() string {
	if x != nil {
		return x.ReserveId
	}
	return ""
}

func (x *Reserve) GetSlotId() string {
	if x != nil {
		return x.SlotId
	}
	return ""
}

func (x *Reserve) GetSlotLabel() string {
	if x != nil {
		return x.SlotLabel
	}
	return ""
}

func (x *Reserve) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Reserve) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type ReserveHistory struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ReserveHistoryId string                 `protobuf:"bytes,1,opt,name=reserve_history_id,json=reserveHistoryId,proto3" json:"reserve_history_id,omitempty"`
	SlotId           string                 `protobuf:"bytes,2,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	SlotLabel        string                 `protobuf:"bytes,3,opt,name=slot_label,json=slotLabel,proto3" json:"slot_label,omitempty"`
	UserId           string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TimestampBegin   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp_begin,json=timestampBegin,proto3" json:"timestamp_begin,omitempty"`
	TimestampEnd     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp_end,json=timestampEnd,proto3" json:"timestamp_end,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReserveHistory) Reset() {
	*x = ReserveHistory{}
	mi := &file_parksense_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveHistory) ProtoMessage() {}

func (x *ReserveHistory) ProtoReflect() protoreflect.Message {
	mi := &file_parksense_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveHistory.ProtoReflect.Descriptor instead.
func (*ReserveHistory) Descriptor() ([]byte, []int) {
	return file_parksense_proto_rawDescGZIP(), []int{3}
}

func (x *ReserveHistory) GetReserveHistoryId() string {
	if x != nil {
		return x.ReserveHistoryId
	}
	return ""
}

func (x *ReserveHistory) GetSlotId() string {
	if x != nil {
		return x.SlotId
	}
	return ""
}

func (x *ReserveHistory) GetSlotLabel() string {
	if x != nil {
		return x.SlotLabel
	}
	return ""
}

func (x *ReserveHistory) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ReserveHistory) GetTimestampBegin() *timestamppb.Timestamp {
	if x != nil {
		return x.TimestampBegin
	}
	return nil
}

func (x *ReserveHistory) GetTimestampEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.TimestampEnd
	}
	return nil
}

type CreateReserveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotId        string                 `protobuf:"bytes,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	SlotLabel     string                 `protobuf:"bytes,2,opt,name=slot_label,json=slotLabel,proto3" json:"slot_label,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReserveRequest) Reset() {
	*x = CreateReserveRequest{}
	mi := &file_parksense_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReserveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReserveRequest) ProtoMessage() {}

func (x *CreateReserveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_parksense_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReserveRequest.ProtoReflect.Descriptor instead.
func (*CreateReserveRequest) Descriptor() ([]byte, []int) {
	return file_parksense_proto_rawDescGZIP(), []int{4}
}

func (x *CreateReserveRequest) GetSlotId() string {
	if x != nil {
		return x.SlotId
	}
	return ""
}

func (x *CreateReserveRequest) GetSlotLabel() string {
	if x != nil {
		return x.SlotLabel
	}
	return ""
}

func (x *CreateReserveRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type CancelReserveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReserveId     string                 `protobuf:"bytes,1,opt,name=reserve_id,json=reserveId,proto3" json:"reserve_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelReserveRequest) Reset() {
	*x = CancelReserveRequest{}
	mi := &file_parksense_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelReserveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelReserveRequest) ProtoMessage() {}

func (x *CancelReserveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_parksense_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelReserveRequest.ProtoReflect.Descriptor instead.
func (*CancelReserveRequest) Descriptor() ([]byte, []int) {
	return file_parksense_proto_rawDescGZIP(), []int{5}
}

func (x *CancelReserveRequest) GetReserveId() string {
	if x != nil {
		return x.ReserveId
	}
	return ""
}

type ParkSetListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParkSets      []*ParkSet             `protobuf:"bytes,1,rep,name=park_sets,json=parkSets,proto3" json:"park_sets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParkSetListResponse) Reset() {
	*x = ParkSetListResponse{}
	mi := &file_parksense_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParkSetListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParkSetListResponse) ProtoMessage() {}

func (x *ParkSetListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_parksense_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParkSetListResponse.ProtoReflect.Descriptor instead.
func (*ParkSetListResponse) Descriptor() ([]byte, []int) {
	return file_parksense_proto_rawDescGZIP(), []int{6}
}

func (x *ParkSetListResponse) GetParkSets() []*ParkSet {
	if x != nil {
		return x.ParkSets
	}
	return nil
}

type ReserveHistoryListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	History       []*ReserveHistory      `protobuf:"bytes,1,rep,name=history,proto3" json:"history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveHistoryListResponse) Reset() {
	*x = ReserveHistoryListResponse{}
	mi := &file_parksense_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveHistoryListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveHistoryListResponse) ProtoMessage() {}

func (x *ReserveHistoryListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_parksense_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveHistoryListResponse.ProtoReflect.Descriptor instead.
func (*ReserveHistoryListResponse) Descriptor() ([]byte, []int) {
	return file_parksense_proto_rawDescGZIP(), []int{7}
}

func (x *ReserveHistoryListResponse) GetHistory() []*ReserveHistory {
	if x != nil {
		return x.History
	}
	return nil
}

type ReserveListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reserves      []*Reserve             `protobuf:"bytes,1,rep,name=reserves,proto3" json:"reserves,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveListResponse) Reset() {
	*x = ReserveListResponse{}
	mi := &file_parksense_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveListResponse) ProtoMessage() {}

func (x *ReserveListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_parksense_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveListResponse.ProtoReflect.Descriptor instead.
func (*ReserveListResponse) Descriptor() ([]byte, []int) {
	return file_parksense_proto_rawDescGZIP(), []int{8}
}

func (x *ReserveListResponse) GetReserves() []*Reserve {
	if x != nil {
		return x.Reserves
	}
	return nil
}

var File_parksense_proto protoreflect.FileDescriptor

const file_parksense_proto_rawDesc = "" +
	"\n" +
	"\x0fparksense.proto\x12\tparksense\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"~\n" +
	"\aParkLot\x12\x1e\n" +
	"\vpark_lot_id\x18\x01 \x01(\tR\tparkLotId\x12)\n" +
	"\x05state\x18\x02 \x01(\x0e2\x13.parksense.LotStateR\x05state\x12\x10\n" +
	"\x03row\x18\x03 \x01(\rR\x03row\x12\x16\n" +
	"\x06column\x18\x04 \x01(\rR\x06column\"\xb7\x01\n" +
	"\aParkSet\x12\x1e\n" +
	"\vpark_set_id\x18\x01 \x01(\tR\tparkSetId\x12&\n" +
	"\x04lots\x18\x02 \x03(\v2\x12.parksense.ParkLotR\x04lots\x12*\n" +
	"\x05state\x18\x03 \x01(\x0e2\x14.parksense.ParkStateR\x05state\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xb3\x01\n" +
	"\aReserve\x12\x1d\n" +
	"\n" +
	"reserve_id\x18\x01 \x01(\tR\treserveId\x12\x17\n" +
	"\aslot_id\x18\x02 \x01(\tR\x06slotId\x12\x1d\n" +
	"\n" +
	"slot_label\x18\x03 \x01(\tR\tslotLabel\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x95\x02\n" +
	"\x0eReserveHistory\x12,\n" +
	"\x12reserve_history_id\x18\x01 \x01(\tR\x10reserveHistoryId\x12\x17\n" +
	"\aslot_id\x18\x02 \x01(\tR\x06slotId\x12\x1d\n" +
	"\n" +
	"slot_label\x18\x03 \x01(\tR\tslotLabel\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12C\n" +
	"\x0ftimestamp_begin\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x0etimestampBegin\x12?\n" +
	"\rtimestamp_end\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ftimestampEnd\"\x88\x01\n" +
	"\x14CreateReserveRequest\x12\x17\n" +
	"\aslot_id\x18\x01 \x01(\tR\x06slotId\x12\x1d\n" +
	"\n" +
	"slot_label\x18\x02 \x01(\tR\tslotLabel\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"5\n" +
	"\x14CancelReserveRequest\x12\x1d\n" +
	"\n" +
	"reserve_id\x18\x01 \x01(\tR\treserveId\"F\n" +
	"\x13ParkSetListResponse\x12/\n" +
	"\tpark_sets\x18\x01 \x03(\v2\x12.parksense.ParkSetR\bparkSets\"Q\n" +
	"\x1aReserveHistoryListResponse\x123\n" +
	"\ahistory\x18\x01 \x03(\v2\x19.parksense.ReserveHistoryR\ahistory\"E\n" +
	"\x13ReserveListResponse\x12.\n" +
	"\breserves\x18\x01 \x03(\v2\x12.parksense.ReserveR\breserves*=\n" +
	"\bLotState\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\b\n" +
	"\x04FREE\x10\x01\x12\f\n" +
	"\bOCCUPIED\x10\x02\x12\f\n" +
	"\bRESERVED\x10\x03*!\n" +
	"\tParkState\x12\n" +
	"\n" +
	"\x06NORMAL\x10\x00\x12\b\n" +
	"\x04FIRE\x10\x012\xdc\x03\n" +
	"\x10ParkSenseService\x12E\n" +
	"\x15StreamIncomingParkLot\x12\x16.google.protobuf.Empty\x1a\x12.parksense.ParkSet0\x01\x12H\n" +
	"\x0eGetAllParkSets\x12\x16.google.protobuf.Empty\x1a\x1e.parksense.ParkSetListResponse\x12D\n" +
	"\rCreateReserve\x12\x1f.parksense.CreateReserveRequest\x1a\x12.parksense.Reserve\x12O\n" +
	"\x15GetUserActiveReserves\x12\x16.google.protobuf.Empty\x1a\x1e.parksense.ReserveListResponse\x12V\n" +
	"\x15GetUserReserveHistory\x12\x16.google.protobuf.Empty\x1a%.parksense.ReserveHistoryListResponse\x12H\n" +
	"\rCancelReserve\x12\x1f.parksense.CancelReserveRequest\x1a\x16.google.protobuf.EmptyB\x1bZ\x19./internal/services/protob\x06proto3"

var (
	file_parksense_proto_rawDescOnce sync.Once
	file_parksense_proto_rawDescData []byte
)

func file_parksense_proto_rawDescGZIP() []byte {
	file_parksense_proto_rawDescOnce.Do(func() {
		file_parksense_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_parksense_proto_rawDesc), len(file_parksense_proto_rawDesc)))
	})
	return file_parksense_proto_rawDescData
}

var file_parksense_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_parksense_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_parksense_proto_goTypes = []any{
	(LotState)(0),                      // 0: parksense.LotState
	(ParkState)(0),                     // 1: parksense.ParkState
	(*ParkLot)(nil),                    // 2: parksense.ParkLot
	(*ParkSet)(nil),                    // 3: parksense.ParkSet
	(*Reserve)(nil),                    // 4: parksense.Reserve
	(*ReserveHistory)(nil),             // 5: parksense.ReserveHistory
	(*CreateReserveRequest)(nil),       // 6: parksense.CreateReserveRequest
	(*CancelReserveRequest)(nil),       // 7: parksense.CancelReserveRequest
	(*ParkSetListResponse)(nil),        // 8: parksense.ParkSetListResponse
	(*ReserveHistoryListResponse)(nil), // 9: parksense.ReserveHistoryListResponse
	(*ReserveListResponse)(nil),        // 10: parksense.ReserveListResponse
	(*timestamppb.Timestamp)(nil),      // 11: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),              // 12: google.protobuf.Empty
}
var file_parksense_proto_depIdxs = []int32{
	0,  // 0: parksense.ParkLot.state:type_name -> parksense.LotState
	2,  // 1: parksense.ParkSet.lots:type_name -> parksense.ParkLot
	1,  // 2: parksense.ParkSet.state:type_name -> parksense.ParkState
	11, // 3: parksense.ParkSet.timestamp:type_name -> google.protobuf.Timestamp
	11, // 4: parksense.Reserve.timestamp:type_name -> google.protobuf.Timestamp
	11, // 5: parksense.ReserveHistory.timestamp_begin:type_name -> google.protobuf.Timestamp
	11, // 6: parksense.ReserveHistory.timestamp_end:type_name -> google.protobuf.Timestamp
	11, // 7: parksense.CreateReserveRequest.timestamp:type_name -> google.protobuf.Timestamp
	3,  // 8: parksense.ParkSetListResponse.park_sets:type_name -> parksense.ParkSet
	5,  // 9: parksense.ReserveHistoryListResponse.history:type_name -> parksense.ReserveHistory
	4,  // 10: parksense.ReserveListResponse.reserves:type_name -> parksense.Reserve
	12, // 11: parksense.ParkSenseService.StreamIncomingParkLot:input_type -> google.protobuf.Empty
	12, // 12: parksense.ParkSenseService.GetAllParkSets:input_type -> google.protobuf.Empty
	6,  // 13: parksense.ParkSenseService.CreateReserve:input_type -> parksense.CreateReserveRequest
	12, // 14: parksense.ParkSenseService.GetUserActiveReserves:input_type -> google.protobuf.Empty
	12, // 15: parksense.ParkSenseService.GetUserReserveHistory:input_type -> google.protobuf.Empty
	7,  // 16: parksense.ParkSenseService.CancelReserve:input_type -> parksense.CancelReserveRequest
	3,  // 17: parksense.ParkSenseService.StreamIncomingParkLot:output_type -> parksense.ParkSet
	8,  // 18: parksense.ParkSenseService.GetAllParkSets:output_type -> parksense.ParkSetListResponse
	4,  // 19: parksense.ParkSenseService.CreateReserve:output_type -> parksense.Reserve
	10, // 20: parksense.ParkSenseService.GetUserActiveReserves:output_type -> parksense.ReserveListResponse
	9,  // 21: parksense.ParkSenseService.GetUserReserveHistory:output_type -> parksense.ReserveHistoryListResponse
	12, // 22: parksense.ParkSenseService.CancelReserve:output_type -> google.protobuf.Empty
	17, // [17:23] is the sub-list for method output_type
	11, // [11:17] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_parksense_proto_init() }
func file_parksense_proto_init() {
	if File_parksense_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_parksense_proto_rawDesc), len(file_parksense_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_parksense_proto_goTypes,
		DependencyIndexes: file_parksense_proto_depIdxs,
		EnumInfos:         file_parksense_proto_enumTypes,
		MessageInfos:      file_parksense_proto_msgTypes,
	}.Build()
	File_parksense_proto = out.File
	file_parksense_proto_goTypes = nil
	file_parksense_proto_depIdxs = nil
}
