// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: parksense.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ParkSenseService_StreamIncomingParkLot_FullMethodName = "/parksense.ParkSenseService/StreamIncomingParkLot"
)

// ParkSenseServiceClient is the client API for ParkSenseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ParkSenseServiceClient interface {
	StreamIncomingParkLot(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ParkSet], error)
}

type parkSenseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewParkSenseServiceClient(cc grpc.ClientConnInterface) ParkSenseServiceClient {
	return &parkSenseServiceClient{cc}
}

func (c *parkSenseServiceClient) StreamIncomingParkLot(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ParkSet], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ParkSenseService_ServiceDesc.Streams[0], ParkSenseService_StreamIncomingParkLot_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, ParkSet]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ParkSenseService_StreamIncomingParkLotClient = grpc.ServerStreamingClient[ParkSet]

// ParkSenseServiceServer is the server API for ParkSenseService service.
// All implementations must embed UnimplementedParkSenseServiceServer
// for forward compatibility.
type ParkSenseServiceServer interface {
	StreamIncomingParkLot(*emptypb.Empty, grpc.ServerStreamingServer[ParkSet]) error
	mustEmbedUnimplementedParkSenseServiceServer()
}

// UnimplementedParkSenseServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedParkSenseServiceServer struct{}

func (UnimplementedParkSenseServiceServer) StreamIncomingParkLot(*emptypb.Empty, grpc.ServerStreamingServer[ParkSet]) error {
	return status.Errorf(codes.Unimplemented, "method StreamIncomingParkLot not implemented")
}
func (UnimplementedParkSenseServiceServer) mustEmbedUnimplementedParkSenseServiceServer() {}
func (UnimplementedParkSenseServiceServer) testEmbeddedByValue()                          {}

// UnsafeParkSenseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ParkSenseServiceServer will
// result in compilation errors.
type UnsafeParkSenseServiceServer interface {
	mustEmbedUnimplementedParkSenseServiceServer()
}

func RegisterParkSenseServiceServer(s grpc.ServiceRegistrar, srv ParkSenseServiceServer) {
	// If the following call pancis, it indicates UnimplementedParkSenseServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ParkSenseService_ServiceDesc, srv)
}

func _ParkSenseService_StreamIncomingParkLot_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ParkSenseServiceServer).StreamIncomingParkLot(m, &grpc.GenericServerStream[emptypb.Empty, ParkSet]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ParkSenseService_StreamIncomingParkLotServer = grpc.ServerStreamingServer[ParkSet]

// ParkSenseService_ServiceDesc is the grpc.ServiceDesc for ParkSenseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ParkSenseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "parksense.ParkSenseService",
	HandlerType: (*ParkSenseServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamIncomingParkLot",
			Handler:       _ParkSenseService_StreamIncomingParkLot_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "parksense.proto",
}
